- README.md
Please also add the license info at the bottom.
> Adding NuGet badge to README.md

- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/TableInfo.cs
Fix issues: #7 and #8 
Enhancement - use context connection for SqlBulkCopy constructor
> Fix issues: #7 (Opened connections are not closed properly) and #8 (Connection is not opened - BulkMerge)

- EFCore.BulkExtensions/DbContextBulkExtensions.cs
- EFCore.BulkExtensions/DbContextBulkTransaction.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/TableInfo.cs
Some minor optimizations - don't stick to UI thread, remove unnecessary Task allocations (async methods).
> Add ConfigureAwait(false) to awaits, optimize out simple async methods

- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs
- EFCore.BulkExtensions/TableInfo.cs
> avoid query cache by creating compiled queries manual

- EFCore.BulkExtensions/SqlBulkOperation.cs
This fixes a problem with ignored properties as described in #89
> Fix issue #89

- EFCore.BulkExtensions/BatchUtil.cs
Ownsone BatchUpdate bug fixed.
> Ownsone BatchUpdate bug fixed

- EFCore.BulkExtensions.Tests/EFCoreBulkUnderlyingTest.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/DbContextUnderlyingExtensions.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
https://github.com/borisdj/EFCore.BulkExtensions/issues/106
> issue#106 Support of underlying connection/transactions/commands

- EFCore.BulkExtensions/TableInfo.cs
This fixes a problem that we had with properties which are marked with [ConcurrencyCheck].
For example
```
public class MyEntity
{
[Key]
public int Id { get; set; }
[Required]
public DateTime CreatedDate { get; set; }
[Required]
public int CreatedBy { get; set; }
[Required]
[ConcurrencyCheck]
public DateTime UpdatedDate { get; set; }
[Required]
public int UpdatedBy { get; set; }
}
```
or
```
public class Person
{
public int PersonId { get; set; }
[ConcurrencyCheck]
public string LastName { get; set; }
public string FirstName { get; set; }
}
```
In the original code the properties with the [ConcurrencyCheck] attribute were treated as "timestamps". On BulkInsert these properties then were excluded from the column-list and no values have been transfered.
I have extended the check for …
> fixed evaluation of timestamp properties

- EFCore.BulkExtensions/SqlBulkOperation.cs
Proposal for fixing Issue #148.
> FIX: Do not use fastmember when entity uses conversions (Issue #148)

- EFCore.BulkExtensions/BatchUtil.cs
#174 Add support for bitwise operators in update expressions
> #174 Add support for bitwise operators

- EFCore.BulkExtensions.Tests/DbDataReaderExtensions.cs
- EFCore.BulkExtensions/DbContextBulkExtensions.cs
- EFCore.BulkExtensions/DbContextBulkTransaction.cs
- EFCore.BulkExtensions/IQueryableBatchExtensions.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/TableInfo.cs
Added cancellation token support + Replaced non-async method calls with their async equivalent where possible + added ConfigureAwait(false) where missing.
> Async method enhancements

- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/TableInfo.cs
There was no progress reporting for SQLite, so I provided one and made it common with SQL Server one.
> Implemented common progress setting logic

- EFCore.BulkExtensions/ObjectReaderEx.cs
- EFCore.BulkExtensions/TableInfo.cs
This allows to insert/update from derived entity colums even an enumerable from the abstract base type is passed into the function
> support for filling columns from derived entities

- EFCore.BulkExtensions.Tests/EFCoreBatchTest.cs
- EFCore.BulkExtensions/BatchUtil.cs
- EFCore.BulkExtensions/IQueryableExtensions.cs
Solution is inspired by
https://github.com/dotnet/efcore/blob/master/src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs#L107
https://github.com/dotnet/efcore/blob/master/src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs#L44
> Support IEnumerable<>.Contains and Any query.

- EFCore.BulkExtensions/SqlBulkOperation.cs
Fixes https://github.com/borisdj/EFCore.BulkExtensions/issues/356. Tagging everyone who has touched this code before @borisdj @PawelGerr 
T**his is a fundamental change so it definitely requires some review/discussion prior to merge**. The diff looks like a lot but this is merely indentation changes - I will annotate the exact lines which have actually changed.
In summary - SQL Server supports the following code out of the box, and as far as I can tell, does NOT use a nested transaction below the application's transaction below:
```
using var transaction = dbContext.Database.BeginTransactionAsync();
dbContext.BulkInsert(entities);
transaction.Commit();
```
*This code does NOT work out of the box with Sqlite.* This is because you need to explicitly specify the `SqliteTransaction` …
> Use ambient SqliteTransaction if available

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/TableInfo.cs
Adds support for properties with converter values in OwnedTypes. (isssue #377)
> Support converted property in owned type

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/TableInfo.cs
Added functionality to discover ForeignKeys that are ShadowProperties.
Also excluded ForeignKey-ShadowProperties from being discovered as discriminators.
All test were run on SQLServer because i currently have nothing else installed...
> Shadow properties as foreign keys

- EFCore.BulkExtensions.Tests/EFCoreBatchTest.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/IQueryableExtensions.cs
Fix bug: when apply batch update or batch delete on a query with User Defined Table Type parameter, an exception will occur (System.ArgumentException : No mapping exists from object type System.Object[] to a known managed provider native type.).
> Fix bug in batch update and batch delete with User Defined Table Type parameter

- EFCore.BulkExtensions/ActivitySources.cs
- EFCore.BulkExtensions/DbContextBulkTransaction.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
This PR instruments the Bulk Operations with Activties. This allows to collect telemetry about the bulk insert performance.
> Add an Activity to all operations.

- EFCore.BulkExtensions.Tests/EFCoreBatchTest.cs
- EFCore.BulkExtensions/BatchUtil.cs
1. Use an updateable CTE in DELETE when the query uses TOP/OFFSET with ORDER BY
2. Strip ORDER BY in DELETE when the query does not use TOP/OFFSET
Fixes https://github.com/borisdj/EFCore.BulkExtensions/issues/301
Fixes https://github.com/borisdj/EFCore.BulkExtensions/issues/399
Notes
* Why not use an updateable CTE for all queries? 
a. Updateable CTE has limitations like only a single main table (no JOINs).
b. Updateable CTE still doesn't allow ORDER without TOP/OFFSET, so stripping ORDER BY (#2) is needed anyway.
* I didn't add support for SQLite
SQLite does not support updateable CTE, it does support a normal CTE and I got something like this working:
```
var entityType = context.Model.FindEntityType(query.ElementType);
var pkeyExpression = entityType.FindPrimaryKey();	
var pkey = …
```
> MSSQL batch delete with order by queries

- EFCore.BulkExtensions.Tests/ValueConverters/ValueConverterTests.cs
- EFCore.BulkExtensions/BatchUtil.cs
This fixes an issue where `BatchUpdate` with an Expression would write the unconverted value to the DB, instead of using the configured ValueConverter.
For example with an Enum property that has a string conversion this would write an integer to the DB instead of a string.
```c#
public enum VcEnum
{
Why,
...
}
cfg.Property(y => y.Enum).HasColumnType("nvarchar(4000)").HasConversion<string>();
...
db.VcModels.BatchUpdate(x => new VcModel
{
Enum = VcEnum.Why
});
```          
wrote `0` to the DB instead of `"Why"`
> Adds support for ValueConverter in BatchUpdate Expression

- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
- EFCore.BulkExtensions.Tests/IncludeGraph/GraphDbContext.cs
- EFCore.BulkExtensions.Tests/IncludeGraph/IncludeGraphTests.cs
- EFCore.BulkExtensions.Tests/IncludeGraph/Model/Asset.cs
- EFCore.BulkExtensions/DbContextBulkTransactionGraphUtil.cs
- EFCore.BulkExtensions/GraphUtil.cs
> Fix issue 520

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions/Helpers/GenericsHelpers.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
- EFCore.BulkExtensions/SqlQueryBuilder.cs
If the input have a value for property that have HasDefaultValueSql, don't skip this property in insert state.
> If the input have a value for property that have HasDefaultValueSql, don't skip this property in insert state

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
Added a test that reproduces #604
> Add geography and geometry persistence test

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
A possible solution to resolve issue #604
> Support sql server geometry type

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
Apply issue #604 fix in EFCore3.1 to master
> Resolve issue #604

- EFCore.BulkExtensions.Tests/BatchUtil/BatchUtilTests.cs
- EFCore.BulkExtensions.Tests/BatchUtil/Issue658.cs
- EFCore.BulkExtensions/BatchUtil.cs
> Use column conversions for default values when generating sql SET segment

- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/TableInfo.cs
> DefiningNavigationName and DefiningEntityType are not supported anymore

- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
They always return null
Same fix as in TableInfo.cs
> DefiningNavigationName and DefiningEntityType are not supported anymore 

- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
Hi, 
I worked on giving support for HierarchyId in EF Core 3.1.
I also added a 3 new tests to the Test Project and new class Category to the TestContext for testing HierarchyId.
Regards
> Added support for HierarchyId in EF Core3.1

- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlAdapter.cs
Solving issue #709 
Merge/MergeAsync internally call insert - this should work for all bulk operations from postgres adapter
> Added progress callback call for postrgres bulk operations

- EFCore.BulkExtensions/SQLAdapters/PostgreSql/SqlQueryBuilderPostgreSql.cs
Sorry for some possible wrong way off doing the PR. not used to push into public repos.
this is not unit tested  as i dont know where the test are for this. but its related to the #742 issue.and i succesfully used this fix in my project, and it can now find the index wit multiple columns
> Fix constraincheck issue in postgress

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/TableInfo.cs
> NullReferenceException when using numeric private key property

- EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlAdapter.cs
> Fix inclusion of default value columns in BulkInsert on postgres

- EFCore.BulkExtensions/DbContextBulkTransactionSaveChanges.cs
… come già presente in altri punti
> changed the DbContextBulkTransactionSaveChanges class adding the doExplicitCommit as in other points.

- EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlAdapter.cs
resolves #777 
Existing behavior has been kept (although it's not clear if this is necessary) used the same approach as in SQL Server.
Have tested locally and works. Unsure of testing strategy however, so no tests in the codebase (the tests don't run locally for me).
> fix: add value conversion to postgres adapter

- EFCore.BulkExtensions/ActivitySources.cs
- EFCore.BulkExtensions/BatchUpdateCreateBodyData.cs
- EFCore.BulkExtensions/BatchUtil.cs
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/DbContextBulkExtensions.cs
- EFCore.BulkExtensions/DbContextUnderlyingExtensions.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/FastProperty.cs
- EFCore.BulkExtensions/IQueryableBatchExtensions.cs
- EFCore.BulkExtensions/IQueryableExtensions.cs
- EFCore.BulkExtensions/InvalidBulkConfigException.cs
- EFCore.BulkExtensions/OwnedTypeUtil.cs
- EFCore.BulkExtensions/SQLAdapters/ISqlDialect.cs
- EFCore.BulkExtensions/SQLAdapters/ISqlOperationsAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlDialect.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/SqlQueryBuilderPostgreSql.cs
- EFCore.BulkExtensions/SQLAdapters/ProgressHelper.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerDialect.cs
- EFCore.BulkExtensions/SQLAdapters/SQLite/SqLiteAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/SQLite/SqLiteDialect.cs
- EFCore.BulkExtensions/SQLAdapters/SQLite/SqlQueryBuilderSqlite.cs
- EFCore.BulkExtensions/SQLAdapters/SqlAdaptersMapping.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/SqlQueryBuilder.cs
- EFCore.BulkExtensions/TableInfo.cs
This PR is to resolve all the XML warnings by adding basic descriptions or suppressing the error where it doesn't make sense to add XML comments.
I have also enabled to setting TreatWarningsAsErrors to prevent any warnings from being checked in to the main project. Reason for this setting is because I strongly feel there should be no warnings, if there is a warning that is not valid it should be suppressed.
> Resolved xml warnings

- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions/ActivitySources.cs
- EFCore.BulkExtensions/BatchUpdateCreateBodyData.cs
- EFCore.BulkExtensions/BatchUtil.cs
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/DbContextBulkExtensions.cs
- EFCore.BulkExtensions/DbContextBulkTransaction.cs
- EFCore.BulkExtensions/DbContextBulkTransactionGraphUtil.cs
- EFCore.BulkExtensions/DbContextBulkTransactionSaveChanges.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/FastProperty.cs
- EFCore.BulkExtensions/GraphUtil.cs
- EFCore.BulkExtensions/Helpers/GenericsHelpers.cs
- EFCore.BulkExtensions/IQueryableBatchExtensions.cs
- EFCore.BulkExtensions/IQueryableExtensions.cs
- EFCore.BulkExtensions/SQLAdapters/ISqlDialect.cs
- EFCore.BulkExtensions/SQLAdapters/ISqlOperationsAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/SqlQueryBuilderPostgreSql.cs
- EFCore.BulkExtensions/SQLAdapters/ProgressHelper.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/SQLite/SqLiteAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/SQLite/SqlQueryBuilderSqlite.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/SqlQueryBuilder.cs
- EFCore.BulkExtensions/TableInfo.cs
This PR is to enable basic nullable support in the project.
1. Enabled nullable support
2. Surpressed nullable warnings in cases where we know the param/prop won't be null
3. Resolved warnings surrounding nullables
4. Threw exceptions in certain cases if the value is nullable
> Enabled nullables

- EFCore.BulkExtensions/ActivitySources.cs
- EFCore.BulkExtensions/BatchUtil.cs
- EFCore.BulkExtensions/DbContextBulkExtensions.cs
- EFCore.BulkExtensions/DbContextBulkTransactionGraphUtil.cs
- EFCore.BulkExtensions/DbContextBulkTransactionSaveChanges.cs
- EFCore.BulkExtensions/GraphUtil.cs
- EFCore.BulkExtensions/IQueryableExtensions.cs
- EFCore.BulkExtensions/OwnedTypeUtil.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlDialect.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/SqlQueryBuilderPostgreSql.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerDialect.cs
- EFCore.BulkExtensions/SQLAdapters/SQLite/SqLiteAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/SQLite/SqLiteDialect.cs
- EFCore.BulkExtensions/SQLAdapters/SqlAdaptersMapping.cs
- EFCore.BulkExtensions/SqlQueryBuilder.cs
- EFCore.BulkExtensions/TableInfo.cs
This PR is to resolve violations being shown (methods needing to be marked as static, and CancellationToken should always be the lass paramater) as well as a few code simplifications.
> Resolved violations and applied simplifications

- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/testsettings.json
- EFCore.BulkExtensions/SQLAdapters/MySql/MySqLAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/MySql/SqlQueryBuilderMySql.cs
adding bulk update and bulk delete methods
> will support also BulkUpdate, BulkDelete and BulkInsertOrUpdate methods for mysql

- EFCore.BulkExtensions.Tests/IncludeGraph/OwnedGraph.cs
The test scenario for https://github.com/borisdj/EFCore.BulkExtensions/issues/919
> added test scenario for deep owned graph #919

- EFCore.BulkExtensions/BulkConfig.cs
* Fix typo in CalculateStats summary.
* Add periods.
> BulkConfig grammar cleanup

- EFCore.BulkExtensions/DbContextBulkTransactionGraphUtil.cs
Checking for an ambient transaction to avoid exception when calling BeginTransaction.
> Supporting ambient transactions with IncludeGraph.

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions/TableInfo.cs
All PrimaryKeysPropertyColumnName values shall be taken into account and not only the first one
> fix issue 882

- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/SqlAdapters/SQLite/SqLiteAdapter.cs
- EFCore.BulkExtensions/TableInfo.cs
The case was descripted in the Unit Test. When the "Category" property added to the Item class, the Bulk Insert operation was failed for SqliteAdpater.
I don't have PG or Mysql insalled. but surely this test works for MS Server and sqlite
> fix: Bulk insert faild when using Shadow FK for sqlite

- EFCore.BulkExtensions/SqlAdapters/MySql/SqlQueryBuilderMySql.cs
> Issue #1087 Solution

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
Ref: [issue](https://github.com/borisdj/EFCore.BulkExtensions/issues/1343)
> Test for issue1343

- EFCore.BulkExtensions/DbContextBulkTransactionSaveChanges.cs
> Modification to detect ambient transactions from System.Transactions in DbContextBulkTransactionSaveChanges.

- EFCore.BulkExtensions/SqlAdapters/MySql/MySqlAdapter.cs
- EFCore.BulkExtensions/SqlAdapters/MySql/MySqlQueryBuilder.cs
> Make MySql adapter respect UseTempDb flag when creating table copies

- EFCore.BulkExtensions.PostgreSql/SqlAdapters/PostgreSql/PostgreSqlAdapter.cs
Done this todo
```
NpgsqlConnection? connection = (NpgsqlConnection?)SqlAdaptersMapping.DbServer.DbConnection; // TODO refactor
bool closeConnectionInternally = false;
if (connection == null)
{
(var dbConnection, closeConnectionInternally) = await OpenAndGetNpgsqlConnectionAsync(context, isAsync, cancellationToken).ConfigureAwait(false);
connection = (NpgsqlConnection)dbConnection;
}
```
> PostgreSqlAdapter refactor todo (issue 1555)

- EFCore.BulkExtensions.Core/TableInfo.cs
- EFCore.BulkExtensions.Tests/TableInfoTests.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
> Resolve AmbiguousMatchException in TableInfo

- EFCore.BulkExtensions.Core/TableInfo.cs
- EFCore.BulkExtensions.Tests/Owned/NestedOwnedTests.cs
Fixed a bug where owned types did not use type mapping converter.
> Fixed owned type value converter

- EFCore.BulkExtensions.PostgreSql/SqlAdapters/PostgreSql/PostgreSqlQueryBuilder.cs
> fix(#1675): fix create temporary table for postgresql

- Directory.Build.props
- EFCore.BulkExtensions.MySql/EFCore.BulkExtensions.MySql.csproj
- EFCore.BulkExtensions.Oracle/EFCore.BulkExtensions.Oracle.csproj
- EFCore.BulkExtensions.PostgreSql/EFCore.BulkExtensions.PostgreSql.csproj
- EFCore.BulkExtensions.SqlServer/EFCore.BulkExtensions.SqlServer.csproj
- EFCore.BulkExtensions.Sqlite/EFCore.BulkExtensions.Sqlite.csproj
- EFCore.BulkExtensions.Tests/BatchUtil/BatchUtilTests.cs
- EFCore.BulkExtensions.Tests/ContextUtil.cs
- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
- EFCore.BulkExtensions.Tests/EFCoreBatchTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBatchTestAsync.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestOracle.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestSaveChanges.cs
- EFCore.BulkExtensions.Tests/IncludeGraph/IncludeGraphTests.cs
- EFCore.BulkExtensions.Tests/IncludeGraph/Issue547.cs
- EFCore.BulkExtensions.Tests/IncludeGraph/OwnedGraph.cs
- EFCore.BulkExtensions.Tests/Owned/InheritedOwnedTests.cs
- EFCore.BulkExtensions.Tests/Owned/NestedOwnedTests.cs
- EFCore.BulkExtensions.Tests/ShadowProperties/ShadowPropertyTests.cs
- EFCore.BulkExtensions.Tests/ShadowProperties/SpDbContext.cs
- EFCore.BulkExtensions.Tests/SqlQueryBuilderOracleTests.cs
- EFCore.BulkExtensions.Tests/SqlQueryBuilderTests.cs
- EFCore.BulkExtensions.Tests/TableInfoTests.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions.Tests/ValueConverters/ValueConverterTests.cs
- EFCore.BulkExtensions.Tests/ValueConverters/VcDbContext.cs
- EFCore.BulkExtensions.sln.DotSettings
Updated ContextUtil to use SqlType as a constructor, rather than a static property.
> Updated ContextUtil configuration updates to DI

- EFCore.BulkExtensions.Core/Batch/BatchUpdateCreateBodyData.cs
- EFCore.BulkExtensions.Core/Batch/BatchUtil.cs
- EFCore.BulkExtensions.Core/Batch/IQueryableExtensions.cs
- EFCore.BulkExtensions.Core/DbContextBulkTransaction.cs
- EFCore.BulkExtensions.Core/DbContextBulkTransactionGraphUtil.cs
- EFCore.BulkExtensions.Core/SqlAdapters/SqlAdaptersMapping.cs
- EFCore.BulkExtensions.Core/SqlAdapters/SqlQueryBuilder.cs
- EFCore.BulkExtensions.Core/SqlBulkOperation.cs
- EFCore.BulkExtensions.Core/TableInfo.cs
- EFCore.BulkExtensions.MySql/SqlAdapters/MySql/MySqlAdapter.cs
- EFCore.BulkExtensions.PostgreSql/SqlAdapters/PostgreSql/PostgreSqlAdapter.cs
- EFCore.BulkExtensions.SqlServer/SqlAdapters/SqlServer/SqlServerAdapter.cs
- EFCore.BulkExtensions.Sqlite/SqlAdapters/Sqlite/SqliteAdapter.cs
Closes #1679 
I tried to implement it with as few changes as possible. I think there are too much calls to the SqlAdaptersMapping and I also do not understand why sometimes the adapters resolve the server, but it is not the goal of the PR to "improve" that.
Some tests are failing but I could not find the root cause yet, perhaps they are just failing in general.
> Provide server more dynamically.

- EFCore.BulkExtensions.PostgreSql/SqlAdapters/PostgreSql/PostgreSqlQueryBuilder.cs
I see this was fixed in v9, but not in v8. Hoping this can be added in since my project is still in Dotnet 8
> Check UseTempDb in Postgres v8

- EFCore.BulkExtensions.MySql/SqlAdapters/MySql/MySqlAdapter.cs
- EFCore.BulkExtensions.MySql/SqlAdapters/MySql/MySqlQueryBuilder.cs
- Implement JOIN between STATISTICS and TABLE_CONSTRAINTS  
- Verify exact column sequence match via GROUP_CONCAT(COLUMN_NAME)
- Wrap in COUNT(*) subquery for deterministic existence checking
> Correct unique index verification query
