borisdj/EFCore.BulkExtensions

- EFCore.BulkExtensions/ObjectReaderEx.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/TableInfo.cs
This is my take on issue #15 - it's not perfect as it potentially can decrease performance for types without shadow properties (probably can add "if" to ObjectReaderEx.Create and return ObjectReader if no shadow properties present).
Also, it uses reflection to get current item out of ObjectReader. The only other option I see is copying entire ObjectReader implementation onto our project to make "current" field protected instead of private which isn't great either.
> Add simple shadow property support

- EFCore.BulkExtensions/SqlQueryBuilder.cs
- EFCore.BulkExtensions/TableInfo.cs
**Steps to reproduce:**
1. Implement DB context with [global query filters](https://docs.microsoft.com/en-us/ef/core/querying/filters).
2. Execute bulk insert method with option SetOutputIdentity=true.
`Context.BulkInsert(entities, new BulkConfig { PreserveInsertOrder = true, BatchSize = 500, SetOutputIdentity = true});`
**Actual result:**
Method throws an exception.
**Expected result:**
No exception should be thrown.
> Fix bulk inserting with option SetOutputIdentity

- EFCore.BulkExtensions/SqlQueryBuilder.cs
- EFCore.BulkExtensions/TableInfo.cs
Fixes issue #33 
Was running a SQL Script checking for identity column and was using wrong column name throwing a SqlException. Uses the existing column mapping to map the primary key property to the actual column name
> Fixes issue with BulkInsert when SetOutputIdentity = true and primary key column name is different than the property name

- EFCore.BulkExtensions.Tests/DbDataReaderExtensions.cs
- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/ObjectReaderEx.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/TableInfo.cs
Added support for ValueConverters and updated the existing unit tests to accommodate a property that had a conversion on it. See issue #39
> Added support for ValueConverters introduced in EFCore v2.1.0

- EFCore.BulkExtensions/BatchUtil.cs
- EFCore.BulkExtensions/IQueryableBatchExtensions.cs
Related to #169 - thanks for your change.
Can we also remove `new()` constraint on Async version of `BatchUpdate` and for `BatchDelete` as well?
> Remove reduntant new() constraint on BatchDelete, BatchDeleteAsync and BatchUpdateAsync

- EFCore.BulkExtensions.Tests/SqlQueryBuilderTests.cs
- EFCore.BulkExtensions/SqlQueryBuilder.cs
- EFCore.BulkExtensions/TableInfo.cs
TableInfo is now aware of the Identity column name.  
HasIdentity now returns true if IdentityColumnName is present.
UpdateEntitiesIdentity now uses IdentityColumnName instead of first primary key.
> Allow SetOutputIdentity to work with composite primary keys

- EFCore.BulkExtensions/BatchUtil.cs
- EFCore.BulkExtensions/IQueryableBatchExtensions.cs
- EFCore.BulkExtensions/IQueryableExtensions.cs
- EFCore.BulkExtensions/SimpleParameterValues.cs
Batch operations: Inner query parameters are passed in the clear
When the original query used for the Batch operation contains parameters, they are passed in the clear (as values instead of query parameters) to the generated SQL query.
Example:
var now = DateTimeOffset.UtcNow;
var query = context.Items.Where(x => x.Id <= maxBatchId);
await query.BatchUpdateAsync(new Item() { LastSeenOn = now });
Expected query:
UPDATE [item] SET [LastSeenOn] = @LastSeenOn FROM [Items] AS [item] WHERE [x].[Id] <= @__maxBatchId_0
Actual query:
UPDATE [item] SET [LastSeenOn] = @LastSeenOn FROM [Items] AS [item] WHERE [x].[Id] <= CAST(1000 AS bigint)
Created an alternative to IQueryable.ToSql() - IQueryable.ToParametrizedSql() that builds the query using parameters instead of direct values. 
The SqlParameter …
> Solves issue #177

- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
When EFCore.BulkExtensions package from version 2.6.0 up - is to be installed in library targeting .NET Standard - it fails to install complaining about 3 libraries being downgraded. I've added them as dependencies and tested that package installation succeeds now.
> Fixed NuGet dependencies for .NET Standard

- EFCore.BulkExtensions.Tests/EFCoreBatchTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBatchTestAsync.cs
- EFCore.BulkExtensions/BatchUtil.cs
Support "TOP(xx)" statement for SQL Server in batch delete and batch update in EFCore 2.2.
This is useful for scenarios in which we have for example a recurring job to delete just a few records each time it runs.
Really like this extension, great job 👍
> [238] add support to TOP statement for SQL server in EFCore 2.2

- EFCore.BulkExtensions.Tests/EFCoreBatchTest.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/IQueryableExtensions.cs
The reflection in IQueryableExtensions didn't work for EFCore 3.1. What do you think?
> BatchDelete works with EFCore 3.1 for SQL Server

- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
Problem:
When you install Microsoft.EntityFrameworkCore.Sqlite 3.1.0 you can see dlls without modify date. It cause to "The DateTimeOffset specified cannot be converted into a Zip file timestamp" when you try to pack project.
Solution:
Update lib version
related problem
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/269
https://github.com/OrchardCMS/OrchardCore/issues/4477
https://github.com/NuGet/Home/issues/7001
> Fix dotnet pack error with Sqlite package

- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
As described at https://github.com/dotnet/SqlClient/issues/262, version 1.1.0 of Microsoft.Data.SqlClient has a bug that can cause deadlocks in async calls, which is fixed in the 1.1.1 release.
refs #281.
> Update Microsoft.Data.SqlClient reference to version 1.1.1

- EFCore.BulkExtensions/SqlBulkOperation.cs
There is an error thrown right now when you have an identity column that is a long type because the identity is explicitly cast to an int. I changed it to only cast to an int if the identity is an int.
> Support long for identity type in sqlite

- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/SqlQueryBuilder.cs
- EFCore.BulkExtensions/TableInfo.cs
Set unique temp table name if needed. In some cases, there is no need to create a unique table name for temp DB (reducing new execution plan creations)
> #326 Set unique temp table name if needed

- EFCore.BulkExtensions/SqlBulkOperation.cs
When using SQLite and a custom Converter that ouputs a null value, we must also convert it to DBNull.Value or it crashes.
> Update SqlBulkOperation.cs for SQLite

- EFCore.BulkExtensions/SqlBulkOperation.cs
I was doing some tests with BulkInsertAsync using Sqlite and fell across what looks like #295, which I think might be because #296 only fixed the sync version of Merge.
This PR just applies the same change to MergeAsync. (which seems to fix my tests, though I don't know enough about how it works to say if this is the best approach)
> Extend the fix for #295 to SqlBulkOperation.MergeAsync

- .gitignore
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/SqlQueryBuilderSqlite.cs
Fix generation of the query when column name differ between model and database. (for exemple bounding_box_id in database and BoundingBoxId in the model)
This pull request is a proposal to fix the issue https://github.com/borisdj/EFCore.BulkExtensions/issues/349
> Fix query generation with auto identity

- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
Adds SourceLink to the project, and updates the included files so that the PDB gets included in the .nupkg file.
refs #344
> Enable SourceLink in the Nuget package

- .editorconfig
- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/TableInfo.cs
PR for issue #253 
The issue still exists in the new version. I've provided tests and bugfixes for both the sync and async operations. There were multiple occurrences that closes the connection that was opened by "someone else" before but that may be not all of them.
Please backport the fixes to version 2.x if the solution is acceptable for you because a lot of companies are still using EF Core 2.x. Thx!
btw. there are/were 4 tests that are failing before my change.
PS: I've added an .editorconfig so the code style of the contributors are maching yours.
> Bulk-Operations should not close an open connection

- EFCore.BulkExtensions/TableInfo.cs
Currently when an entity type with no Key is used it would throw a NullReferenceException. This change instead throws an InvalidOperationException with message "EntitySet for Type: { type.Name } must contain a Primary Key"
> Provide helpful exception message when table contains no primary key

- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/SqlQueryBuilderSqlite.cs
- EFCore.BulkExtensions/TableInfo.cs
@borisdj 
I tested this with an `InsertAsync` operation on an entity that was configured with `HasNoKey()`. It appears to work successfully. That said, I don't know the full context of this code, but it seems in line with the recent changes made in 121d2d5.
> Fix NullReferenceException on bulk operations on entities with no keys

- EFCore.BulkExtensions/BatchUtil.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
Added a work around to BatchUtils.GetBatchSql(..) to first split any leading comments/whitespace from the main sql query before attempting to parse it.
> Issue #333 - Split leading comments

- EFCore.BulkExtensions/BatchUtil.cs
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/SqlBulkOperation.cs
- EFCore.BulkExtensions/SqlClientHelper.cs
- EFCore.BulkExtensions/TableInfo.cs
added ability to support both System.Data.SqlClient and Microsoft.Data.SqlClient by coersing parameter and bulk operation objects to the correct type.  Microsoft.Data.SqlClient should continue to work as it has, but if the DbContext has a System.Data.SqlClient connection, that will now work, where it previously did not.
> added back System.Data.SqlClient support

- EFCore.BulkExtensions/DbContextBulkTransaction.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
* The method `EFCore.BulkExtensions.SqlBulkOperation.TruncateAsync` was missing a `CancellationToken`parameter. It has been added and forwarded to `ExecuteSqlRawAsync`.
* Both `MergeAsync` and `ReadAsync` take a `CancellationToken` parameter. This commit properly passes the cancellation token to the `ExecuteSqlRawAsync` method when dropping the temporary table.
> Properly pass cancellation tokens

- EFCore.BulkExtensions/SqlBulkOperation.cs
Found by enabling code analysis by adding `<AnalysisLevel>latest</AnalysisLevel>` in the project file and using the .NET 5.0.101 SDK.
See also https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2200
> Keep stack trace information when rethrowing exceptions

- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs
- EFCore.BulkExtensions.Tests/TestExample.sql
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/SqlQueryBuilder.cs
- EFCore.BulkExtensions/TableInfo.cs
This PR fixes a bug where the following methods fail if an output table is used (e.g. `CalculateStats` is `true`):
- BulkDelete
- BulkDeleteAsync
- BulkInsertOrUpdateOrDelete
- BulkInsertOrUpdateOrDeleteAsync
The bug is caused by the fact that the `MERGE` statement does not output anything through the `INSERTED` collection for deleted records. Instead, it outputs those records in the `DELETED` collection. Therefore, when using `INSERTED`, an error about not being able to insert a `NULL` value is thrown.
I fixed the bug by using the `COALESCE` operator, which is (at least) available in MS Sql Server, Sqlite, PostgreSQL and MySql. When a value in the `INSERTED` collection is `NULL`, it falls back to the corresponding value in the `DELETED` collection.
Additionally, this PR fixes the …
> Fix bulk delete with output table and add deletions to statistics

- EFCore.BulkExtensions/TableInfo.cs
- EF Core 5 has multiple DbContext.Set methods that cause GetMethod to throw an AmbiguousMatchException
- Use Expression.Call overload that takes instance, method name, generic types and arguments
Closes #443
> Update TableInfo to not use GetMethod so it's compatible with EF Core 5

- .gitignore
- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
- EFCore.BulkExtensions.Tests/EFCoreBulkUnderlyingTest.cs
- EFCore.BulkExtensions.Tests/ShadowProperties/ShadowPropertyTests.cs
- EFCore.BulkExtensions.Tests/ShadowProperties/SpDbContext.cs
- EFCore.BulkExtensions.Tests/ShadowProperties/SpModel.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions.Tests/testsettings.json
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/SQLite/SqLiteAdapter.cs
Closes #470 
Add (normal) Shadow Property support when BulkConfig.EnableShadowProperties is true. You can now add Shadow Properties to your model and persist the values without an error.
```
using var db = new ExampleDbContext();
db.BulkInsertOrUpdate(this.GetTestData(db).ToList(), new BulkConfig
{
EnableShadowProperties = true
});
private IEnumerable<SpModel> GetTestData(DbContext db)
{
var one = new SpModel();
db.Entry(one).Property(SpModel.SpLong).CurrentValue = (long)10;
db.Entry(one).Property(SpModel.SpNullableLong).CurrentValue = null;
db.Entry(one).Property(SpModel.SpDateTime).CurrentValue = new DateTime(2021, 02, 14);
yield return one;
}
```
This disables the automatic discrimator feature, you will have to use manual model method instead.
Add testsettings.json with support for …
> Add (normal) Shadow Property support when BulkConfig.EnableShadowProperties is true

- .gitignore
- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
- EFCore.BulkExtensions.Tests/EFCoreBulkUnderlyingTest.cs
- EFCore.BulkExtensions.Tests/ShadowProperties/ShadowPropertyTests.cs
- EFCore.BulkExtensions.Tests/ShadowProperties/SpDbContext.cs
- EFCore.BulkExtensions.Tests/ShadowProperties/SpModel.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions.Tests/ValueConverters/ValueConverterTests.cs
- EFCore.BulkExtensions.Tests/ValueConverters/VcDbContext.cs
- EFCore.BulkExtensions.Tests/ValueConverters/VcModel.cs
- EFCore.BulkExtensions.Tests/testsettings.json
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/SQLite/SqLiteAdapter.cs
- EFCore.BulkExtensions/TableInfo.cs
Closes #438 
ValueConversion will now work correctly with pre-defined conversions.
```cs
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
modelBuilder
.Entity<Rider>()
.Property(e => e.Mount)
.HasConversion<string>();
}
```
> Support for ValueConverters defined using Pre-defined conversions

- EFCore.BulkExtensions/BatchUtil.cs
Fixes the AmbiguousMatchException error that occurs with EF core 5 when doing bulk operations.
https://github.com/borisdj/EFCore.BulkExtensions/issues/466
> Fix the AmbiguousMatchException with EF core 5

- EFCore.BulkExtensions.Tests/SqlQueryBuilderTests.cs
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/SqlQueryBuilder.cs
- EFCore.BulkExtensions/TableInfo.cs
- README.md
Add option to exclude properties from the insert and/or update portions in BulkInsertOrUpdate method.
Let's say we have CreationDate/CreationBy properties - it should be inserted but never updated. We also have UpdateDate/UpdateBy properties - It should update when the row is updated but not because those values were updated. The four new properties **PropertiesToIncludeOnCompare**, **PropertiesToExcludeOnCompare**, **PropertiesToIncludeOnUpdate**, and **PropertiesToExcludeOnUpdate** allow for those columns to be specified. An added benefit of these new features is that even if they are not explicitly implimented by the user, *MERGE* performance is greatly improved. One of the slowest operations on a database is writing. The *EXISTS / EXCEPT* clause on the *MERGE* command will now only …
> Add option to exclude properties from the insert and/or update portions in BulkInsertOrUpdate method.

- EFCore.BulkExtensions/DbContextBulkTransaction.cs
This fixes a Bug I introduced in my last Pullrequest. The Async Extensions report the end of the Activity too early, because the inner call is not awated.
> Fix async Activites.

- EFCore.BulkExtensions.Tests/IncludeGraph/GraphDbContext.cs
- EFCore.BulkExtensions.Tests/IncludeGraph/IncludeGraphTests.cs
- EFCore.BulkExtensions.Tests/IncludeGraph/Model/Asset.cs
- EFCore.BulkExtensions.Tests/IncludeGraph/Model/Spare.cs
- EFCore.BulkExtensions.Tests/IncludeGraph/Model/WorkOrder.cs
- EFCore.BulkExtensions.Tests/IncludeGraph/Model/WorkOrderSpare.cs
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/DbContextBulkTransaction.cs
- EFCore.BulkExtensions/DbContextBulkTransactionGraphUtil.cs
- EFCore.BulkExtensions/GraphUtil.cs
- EFCore.BulkExtensions/InvalidBulkConfigException.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
- EFCore.BulkExtensions/TableInfo.cs
Insert, update or merge the entire entity object graph. Does not support Sqlite due to how its set output identity = true implementation works.
```csharp
private static WorkOrder WorkOrder1 = new WorkOrder
{
Description = "Fix belt",
Asset = new Asset
{
Description = "MANU-1",
Location = "WAREHOUSE-1"
},
WorkOrderSpares =
{
new WorkOrderSpare
{
Description = "Bolt 5mm x5",
Quantity = 5,
Spare = new Spare
{
PartNumber = "MZD 5mm",
Barcode = "12345"
}
},
new WorkOrderSpare
{
Description = "Bolt 10mm x5",
Quantity = 5,
Spare = new Spare
{
PartNumber = "MZD 10mm",
Barcode = "222655"
}
}
}
};
private IEnumerable<WorkOrder> GetTestData(DbContext db)
{
yield return WorkOrder1;
}
var testData = this.GetTestData(db).ToList();
await db.BulkInsertOrUpdateAsync(testData, new BulkConfig
{
IncludeGraph …
```
> Add ability to insert, update or merge the entity object graph using BulkConfig.IncludeGraph = true

- EFCore.BulkExtensions/SqlQueryBuilder.cs
- EFCore.BulkExtensions/SqlQueryBuilderSqlite.cs
- EFCore.BulkExtensions/TableInfo.cs
BulkInsert problem when primary key has be defined ColumnName and SetOutputIdentity is true.
Problem:
Mapping sample:
builderModel.ToTable("TableSample", "dbo");
builderModel.Property(x => x.Id)
.HasColumnName("ID_TS")
.IsRequired();
builderModel.HasKey(x => x.Id);
.
.
. 
Select generated on TempTable:
SELECT [r].[ID_TS], ...
FROM (
SELECT [ID_TS], ... FROM [dbo].[TableSample431421f7Output] WHERE **_[Id]_** IS NOT NULL
) AS [r]
ORDER BY [r].[ID_TS]
Generated "where" with property name than [ID_TS] (property column name).
> BulkInsert problem when primary key has be defined ColumnName and SetOutputIdentity is true.

- EFCore.BulkExtensions.Tests/ValueConverters/ValueConverterTests.cs
- EFCore.BulkExtensions.Tests/ValueConverters/VcDbContext.cs
- EFCore.BulkExtensions.Tests/ValueConverters/VcModel.cs
- EFCore.BulkExtensions/BatchUpdateCreateBodyData.cs
- EFCore.BulkExtensions/IQueryableExtensions.cs
Hello again :)
When using something like:
```c#
var date = new LocalDate(2020, 3, 21);
dbContext.Model.Where(x => x.LocalDate > date).BatchDelete()
```
I got this exception:
```c#
System.ArgumentException: No mapping exists from object type EFCore.BulkExtensions.Tests.ValueConverters.LocalDate to a known managed provider native type.
at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromType(Type dataType)
at Microsoft.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
at Microsoft.Data.SqlClient.SqlParameter.get_DbType()
at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlServerDialect.ReloadSqlParameters(DbContext context, List`1 sqlParameters)
at …
```
> Fix BatchDelete and BatchUpdate with where expression and ValueConverter

- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs
- EFCore.BulkExtensions/DbContextBulkTransaction.cs
Bugfix for `BulkInsertOrUpdateOrDelete` that wasn't deleting existing entities from the DB when there were 0 entities to insert/update.
I briefly considered adding a fast path like
```c#
if (entities.Count > 0)
{
SqlBulkOperation.Merge(...);
}
else
{
IQueryable<TEntity> queryable = context.Set<TEntity>().IgnoreQueryFilters();
if (bulkConfig.SynchronizeFilter != null)
{
queryable = queryable.Where(bulkConfig.SynchronizeFilter);
}
queryable.BatchDelete();
}
```
but then reasoned that it might be better to keep things simple and if the caller really wants the performance benefit, he can do it himself easily.
> BulkInsertOrUpdateOrDelete should delete when no entities to insert or update

- EFCore.BulkExtensions.Tests/IncludeGraph/IncludeGraphTests.cs
- EFCore.BulkExtensions.Tests/IncludeGraph/Issue547.cs
- EFCore.BulkExtensions/DbContextBulkTransactionGraphUtil.cs
- EFCore.BulkExtensions/GraphUtil.cs
- EFCore.BulkExtensions/OwnedTypeUtil.cs
- EFCore.BulkExtensions/TableInfo.cs
Resolves #547 
OwnedTypes mapped to a separate table is now supported generally
OwnedType's properties mapped into the owner's table are now available in the PropertyColumnNamesCompareDict, so that changes to owned types properties will be saved to the database when doing an update / merge
IncludeGraph - OwnedType's owner now considered dependent on the OwnedType despite EFCore relational model being the inverse for correct topological sorting
IncludeGraph - OwnedTypes mapped to owner's table will be skipped when bulk saving the object graph (as they are part of their owner's schema instead)
> Various OwnedType fixes and resolve issue 547

- EFCore.BulkExtensions/GraphUtil.cs
Prevents a null reference error when inserting a graph of entities which have navigations that are ignored or unmapped in the DbContext.
> When inserting an entity graph, ignore properties / navigations which are not mapped to the db context

- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
So that the SQLite tests pass also on Linux and macOS
Otherwise it fails with a System.DllNotFoundException:
> Unable to load shared library 'winsqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libwinsqlite3, 1): image not found
> Use SQLitePCLRaw.bundle_e_sqlite3 instead of SQLitePCLRaw.bundle_winsqlite3

- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
Some members have XML documentation in code, but it is not included into produced NuGet packages. This PR fixes it.
> Include XML documentation in the NuGet package.

- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
- EFCore.BulkExtensions.Tests/EFCoreBatchTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBatchTestAsync.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions.Tests/TestDbCommandInterceptor.cs
- EFCore.BulkExtensions/BatchUtil.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/TableInfo.cs
Fix For Issue #596 
* Added a new `BatchUpdateAsync_correctly_specifies_AnsiString_type_on_the_sql_parameter` test case that verifies the sql parameter type matches the expected `DbType.AnsiString` / `SqlDbType.VarChar` in both the `.Where(expresion)` and the `.BatchUpdateAsync(model => expression)`.
* Updated the `BatchUtil` logic that builds the sql parameters for the `BatchUpdate` / `BatchUpdateAsync` methods. The logic now first attempt to find and use the entity framework `RelationalTypeMapping.CreateParameter(..)` call for the column/property before falling back on direct instantiation of a db parameter.
> Fix For Issue 596 - Correct BatchUpdate SqlParameter Type

- EFCore.BulkExtensions.Tests/CompilerServicesPolyfill.cs
- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
- EFCore.BulkExtensions.Tests/EFCoreBatchTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBatchTestAsync.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions.Tests/TestDbCommandInterceptor.cs
- EFCore.BulkExtensions/BatchUtil.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/SqlClientHelper.cs
- EFCore.BulkExtensions/TableInfo.cs
**Fix For Issue #596**
* Added a new `BatchUpdateAsync_correctly_specifies_AnsiString_type_on_the_sql_parameter` test case that verifies the sql parameter type matches the expected `DbType.AnsiString` / `SqlDbType.VarChar` in both the `.Where(expresion)` and the `.BatchUpdateAsync(model => expression)`.
* Updated the `BatchUtil` logic that builds the sql parameters for the `BatchUpdate` / `BatchUpdateAsync` methods. The logic now first attempt to find and use the entity framework `RelationalTypeMapping.CreateParameter(..)` call for the column/property before falling back on direct instantiation of a db parameter.
> BatchUpdate Preserve Correct SqlParameter Type - Resolves Issue #596

- EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlAdapter.cs
Instead of `Write`'ing just value also provide column type name when
available. In this case correct column type will be used for CLR
types that are not natively supported or mapped. While this pretty
much fixes the issue #67 (specifically https://github.com/borisdj/EFCore.BulkExtensions/issues/67#issuecomment-982876139 ) , relying on final column
type can lead to issues when assumed type handler doesn't match the actual type.
For example `uint32` has pg type `bigint`, but default handler for this
type is `Int64Handler` which doesn't handle `uint32`.
But regardless of that, this should fix majority of issues with CLR type mapping.
Also I am not entirely sure whats the pattern with using non-async variants inside
async functions. Especially when nested non-async variants call async …
> Fix Postgres BulkInsert CLR type matching

- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlAdapter.cs
- EFCore.BulkExtensions/TableInfo.cs
Reverts change done in https://github.com/borisdj/EFCore.BulkExtensions/commit/e70de346179c3c425e3f765b11071b02743c69cc that modified `timestamp with time zone` to `timestamp`.
This shouldnt be done as the timestamp change is intentional and was introduced in Npgsql 6 to set some constraints on how `DateTime` is used/communicated with Postgres.
See:
- https://www.npgsql.org/doc/release-notes/6.0.html#timestamp-rationalization-and-improvements
- https://www.roji.org/postgresql-dotnet-timestamp-mapping
Error in the comment is correct and should have been corrected in code rather than in the library code, as it notifies user that incorrect assumptions are made regarding date time usage. It also breaks code that uses `DateTimeOffset` for `timestamp with time zone` as Npgsql picks …
> Remove timestamptz type modification

- EFCore.BulkExtensions/FastProperty.cs
Get method returns default object when instance is null. Set method checks to see if the value passed in is not default before it assignes it.
> Safety checks for Get and Set methods.

- EFCore.BulkExtensions.Tests/ShadowProperties/ShadowPropertyTests.cs
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/SQLite/SqLiteAdapter.cs
Added an alternative method of supplying values for shadow properties.
In my use case, I only need to set IsDelete to false for soft deletes and discriminator columns.
Using the function will save memory as not needing to add the entity to the EF change tracking.
> Added global function to return shadow property values

- EFCore.BulkExtensions.Tests/EFCoreBulkUnderlyingTest.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
Corrections:
- added the disposing of the MemoryStream and BinaryWriter according to klemmchr suggestions.
- corrected the GetOptions for EFCoreBulkUnderlyingTest test to support HierachyId
> Ef core3.1 Dispose MemoryStream and BinaryWriter

- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
Issue: https://github.com/borisdj/EFCore.BulkExtensions/issues/723
Adding `InsertOrUpdateDelete` output optimization commit into the V5 version of the branch. Original commit here for reference: https://github.com/borisdj/EFCore.BulkExtensions/commit/4c525151bbc24d97dfd1d532dba31a18eea067df
Ensures that only `InsertOrUpdateDelete` applies the `AlterTableColumnsToNullable` clause on the output table
Let me know if anything else should be added in here. Thanks!
> InsertOrUpdateDelete Output optimization

- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkUnderlyingTest.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
I added the changes I did for the EF Core 3.1 version to the master
Using EntityFrameworkCore.SqlServer.HierarchyId Version=3.0.0
> Added support for HierarchyId to the master version

- EFCore.BulkExtensions.Tests/BatchUtil/BatchUtilTests.cs
- EFCore.BulkExtensions.Tests/BatchUtil/Issue658.cs
- EFCore.BulkExtensions/BatchUtil.cs
Fixes #658 
Original fix written by @fdahlen's for v5 and v6
> ISSUE-658 Use column conversions for default values when generating sql SET segment

- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
expose GetDataTable to public
needed because implement costume logic based on it
> expose GetDataTable to public

- EFCore.BulkExtensions/SQLAdapters/PostgreSql/SqlQueryBuilderPostgreSql.cs
`tableInfo.PropertyColumnNamesUpdateDict` maps model/POCO property names (key) to database column names (value), and `GetColumnList()` returns database column names, thus we need to match the dictionary entries by value and not key, when selecting which columns should have their values updated.
> Fix PropertiesToExcludeOnUpdate column selection issue with postgres.

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlAdapter.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/SqlQueryBuilderPostgreSql.cs
- EFCore.BulkExtensions/SpanSplitExtensions.cs
- EFCore.BulkExtensions/TableInfo.cs
Make owned types (in same table) work in PostgreSQL.
Fix identity annotation identification. Fixes #795 and #695 and #770 and #566 and regression from #772. With passing unit test.
@borisdj
> Make owned types (in same table) work in PostgreSQL.

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs
Hi,
I found, that Owened Types that contain spatial data like
```
[Owned]
public class TrackerLocation
{
public string LocationName { get; set; } = null!;
public Point Location { get; set; } = null!;
}
```
are failing when used in types that are Bulk Inserted/Updated.
The problem was, that the Geometry Logic, that is used in normal Properties, was not used on Properties of Owned Types.
I added that logic and created a Unit Test for it.
It is also only for SQL Server (since the Geometry Handling for normal Properties is only working in SQL Server)
> Owned types with spatial data

- EFCore.BulkExtensions.Tests/SqlQueryBuilderPostgreSqlTests.cs
- EFCore.BulkExtensions/SQLAdapters/PostgreSql/SqlQueryBuilderPostgreSql.cs
Fix for issue 904 (PostgreSql):
Problems
- `BulkInsertOrUpdate` fails when `PropertiesToIncludeOnUpdate` contains empty list
- `BulkInsertOrUpdate` fails when `PropertiesToIncludeOnUpdate` contains same as `UpdateByProperties`
Fix:
- Replace `DO UPDATE SET <empty>` with `DO NOTHING` to provide valid sql
- Add `LIMIT 1` before `ON CONFLICT` to prevent `ON CONFLICT DO UPDATE command cannot affect row a second time`
- Add a unit test case to ensure, the handling is correct
Concerns with this PR:
- Please double re-check, that `LIMIT 1` does not have unwanted side effects in other cases
Thank you.
> fix #904 - bulk update on postgres insert only

- README.md
- Remove duplicate `EnableShadowProperties`
- Replace tabs with spaces
- Move right hand properties under header
- Make top header and bottom footer equal and full width
> Tidy up BulkConfig arguments in README

- .editorconfig
- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
- EFCore.BulkExtensions/DbContextBulkTransaction.cs
- EFCore.BulkExtensions/DbContextBulkTransactionGraphUtil.cs
- EFCore.BulkExtensions/DbContextBulkTransactionSaveChanges.cs
- EFCore.BulkExtensions/SqlAdapters/MySql/MySqlAdapter.cs
- EFCore.BulkExtensions/SqlAdapters/PostgreSql/PostgreSqlAdapter.cs
- EFCore.BulkExtensions/SqlAdapters/SQLite/SqLiteAdapter.cs
- EFCore.BulkExtensions/SqlBulkOperation.cs
Also set the CA2007 severity as warning which will end up as an error since `TreatWarningsAsErrors` is enabled. (But disable them in the test project where they are not required.)
See also [Overview of .NET source code analysis][1] for more information about the .NET analyzers and how to configure them.
[1]: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview
> Add missing .ConfigureAwait(false) everywhere

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/SqlAdapters/SQLite/SqLiteAdapter.cs
- EFCore.BulkExtensions/SqlAdapters/SqlServer/SqlServerAdapter.cs
- EFCore.BulkExtensions/TableInfo.cs
- README.md
Hi!
Proposal for #571 'Return all existing entities from BulkRead'.
> Added ReplaceReadEntities property to BulkConfig (#571).

- EFCore.BulkExtensions/TableInfo.cs
Expanded the condition in TableInfo to load data even when we don't have a identity column, but still want TimeStamps to be handled
> TimeStamp on tables without indentity #1004

- EFCore.BulkExtensions/Helpers/GenericsHelpers.cs
- EFCore.BulkExtensions/SqlAdapters/PostgreSql/PostgreSqlAdapter.cs
Skip default value resolution for navigation properties and remove unnecessary call in PostgreSqlAdapter
fixes https://github.com/borisdj/EFCore.BulkExtensions/issues/1075
> fix issue 1075

- EFCore.BulkExtensions.Tests/SqlQueryBuilderPostgreSqlTests.cs
- EFCore.BulkExtensions/SqlAdapters/PostgreSql/SqlQueryBuilderPostgreSql.cs
Fixes #1006 
BulkUpdate fails in postgres with not-null constraints for excluded columns
> Fix Postgres BulkUpdate

- EFCore.BulkExtensions/SqlAdapters/SqlServer/SqlServerAdapter.cs
In some rare cases, an `ArgumentOutOfRangeException` is thrown by `System.Linq.Enumerable.ElementAt[TSource]` when `SqlOperationsServerAdapter.GetDiscriminatorColumn` method is called. This PR fixes it.
> Fix ArgumentOutOfRangeException in SqlOperationsServerAdapter

- EFCore.BulkExtensions/TableInfo.cs
In my case (SqlServer), when this change resolve a bug when has a GlobalQueryFilter and use BulkInsert with SetOutputIdentity.
Maybe resolve some open issues about SetOutputIdentity (including for another database #793)
> Fix some cases when IgnoreGlobalQueryFilters is true (SetOutputIdentity)

- EFCore.BulkExtensions/TableInfo.cs
Fix for Postgresql schemas, when schema is set in a Search Path parameter of a connection string.
Without this the Search Path is ignored (we set it at runtime - multitenant app) and defaults to "public", which in our case is wrong.
https://www.npgsql.org/doc/connection-string-parameters.html#misc
Examples:
| Connection String | Default Schema |
| --- | --- |
| `Host=myserver;Username=mylogin;Password=mypass;Database=mydatabase;SearchPath=myschema` | `myschema` |
| `Host=myserver;Username=mylogin;Password=mypass;Database=mydatabase;SearchPath=myschema,public` | `myschema` |
| `Host=myserver;Username=mylogin;Password=mypass;Database=mydatabase` | `public` |
> Get Postgresql default schema from Search Path

- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs
- EFCore.BulkExtensions/SqlAdapters/SqlQueryBuilder.cs
When using SetSynchronizeSoftDelete option the query fail with the following message.
> Incorrect syntax near ']'
After dumping the sql and locating the place in the code where the problematic statement was build, it appear that there is an hardcoded 'i' value instead of a table alias.
https://github.com/borisdj/EFCore.BulkExtensions/blob/b622a0c1fac2002a8cc62b9c7847762d0871e901/EFCore.BulkExtensions/SqlAdapters/SqlQueryBuilder.cs#L403
So if the generated alias of the entity is 'i' (like in the current unit test) it's works.
But if not the replace fail and an invalid sql statement is generated.
This fix replace the hardcoded value with the correct table alias for the update statement used when the SetSynchronizeSoftDelete is defined fixing the issue.
> Fix SetSynchronizeSoftDelete option

- EFCore.BulkExtensions/SqlAdapters/SqlQueryBuilder.cs
Found another bug in the soft delete feature.
The newline \r\n was hardcoded in the code.
It is problematic as it's platform dependent so it currently only works on Windows.
Replaced it with Environment.Newline to fix that.
> Fix soft delete feature on linux by using cross-platform NewLine

- EFCore.BulkExtensions.Tests/IncludeGraph/IncludeGraphTests.cs
- EFCore.BulkExtensions/DbContextBulkTransactionGraphUtil.cs
fixes #1340
In the `ExecuteWithGraphAsync` method, a record of StatsInfo is now kept, and the numbers from `bulkConfig.StatsInfo` are added to that record after each "merge" action. `bulkConfig.StatsInfo` is then replaced with that recorded StatsInfo at the end.
I've also updated `IncludeGraphTests.BulkInsertOrUpdate_EntityWithNestedObjectGraph_SavesGraphToDatabase` to test this.
Another option would be to always add the numbers to the stats if they already exist inside the `TableInfo.LoadOutputDataAsync` method instead of overwriting them there each time. This is probably even cleaner, but might have further reaching consequences (backward compatibility issues?) as that code is used from more places...
> Fix Stats when both IncludeGraph and CalculateStats are true

- EFCore.BulkExtensions/DbContextBulkTransactionSaveChanges.cs
Reverse deletion order of outer enumerable of entity groups rather than inner lists of entities when invoking BulkSaveChangesAsync.
#899
> Proposed fix to SaveChangesAsync entity ordering for deletions

- EFCore.BulkExtensions.Tests/Owned/NestedOwnedTests.cs
- EFCore.BulkExtensions/SqlAdapters/SqlServer/SqlServerAdapter.cs
- EFCore.BulkExtensions/TableInfo.cs
Fixes #1351
Owned types are now recursively checked for nested owned types.
This "recursive check" had to happen in 3 places. Once in TableInfo, and 2 times in SqlServerAdaptor.
I have implemented it using a local function to keep the code more or less in the same shape.
This is now only fully implemented for sql server. The other adaptors will also need to be updated to take advantage of this (but they should keep working like before without any changes).
From debugging and implementing this, it feels like there's probably quite some code in SqlServerAdaptor that can be removed as the properties on tableInfo can be used for a lot of the things that are "re-calculated" there now, I suppose? (Probably leftovers from previous refactors, that haven't made it to the SqlServerAdaptor?) …
> Add support for nested owned types

- EFCore.BulkExtensions/SqlAdapters/PostgreSql/PostgreSqlAdapter.cs
BulkInsert (PostgreSql) row with decimal[] column throws: System.InvalidCastException: 'Writing values of 'System.Decimal[]' is not supported for parameters having DataTypeName 'numeric'.'
Entity type to reproduce:
```
public class Row
{
public int Id { get; set; }
public required decimal[] Values { get; set; }
}
```
> PostgreSqlAdapter, correct columnType for decimal[]

- EFCore.BulkExtensions/SqlAdapters/PostgreSql/PostgreSqlQueryBuilder.cs
When multiple fields are provided the existing query gives the count which is greater than 1. This later causes a new constraint creation. This in its' turn cannot be run in concurrent environment.
> fix(postgre): correctly count number of constraints

- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
- EFCore.BulkExtensions/SqlAdapters/Sqlite/SqliteAdapter.cs
Hi,
Issue 1023 and 1214 are mentioned as fixed but it doesn't seems to be the case.
When inserting a point type with bulk insert the following exception is throw
>  No mapping exists from object type NetTopologySuite.Geometries.Point to a known managed provider native type.
This is because only Geometry and LineString types are handled by the [adapter](https://github.com/kvpt/EFCore.BulkExtensions/blob/7de0593127f779c6e3a928b6c7f74fa56f7457bf/EFCore.BulkExtensions/SqlAdapters/Sqlite/SqliteAdapter.cs#L495).
A more robust approach is to use instead the Geometry type only and rely on polymorphism.
However this alone doesn't work, the error is now
> '<GeoColumn> violates Geometry constraint [geom-type or SRID not allowed]'
To solve this we have two things to do :
- The first is to the right …
> Correct bulk operation on Sqlite Geometry types

- EFCore.BulkExtensions/TableInfo.cs
Fix for bulk insert using include graph when `PKs` are `string` or `Guid`.
This PR addresses the issue #1314 
When the parent object has a `string` or `Guid` `PK` the order of the entities in the `entitiesWithOutputIdentity` variable is different as the order when the entities were inserted. Because the `ORDER BY` on the DB behaves different then the `OrderBy()` in C# we have to order both variables `entitiesWithOutputIdentity` and `entities` by the `PK`. With this fix the child entites are assigned with the correct `PK`.
> Fix for bulk insert using include graph

- EFCore.BulkExtensions/TableInfo.cs
allProperties.First(p => p.Name == b).GetColumnName(ObjectIdentifier) throws uninformative no elements exception when bulkConfig has an unexisting propertyName in the UpdateByProperties list
> Library creates uninformative exception when UpdateByProperties list has wrong (enexisting) property names

- EFCore.BulkExtensions.PerProvider/EFCore.BulkExtensions.MySql/EFCore.BulkExtensions.MySql.csproj
- EFCore.BulkExtensions.PerProvider/EFCore.BulkExtensions.PostgreSql/EFCore.BulkExtensions.PostgreSql.csproj
- EFCore.BulkExtensions.PerProvider/EFCore.BulkExtensions.Sqlite/EFCore.BulkExtensions.Sqlite.csproj
- EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions/Batch/BatchUpdateCreateBodyData.cs
- EFCore.BulkExtensions/Batch/BatchUtil.cs
- EFCore.BulkExtensions/Batch/IQueryableBatchExtensions.cs
- EFCore.BulkExtensions/Batch/IQueryableExtensions.cs
- EFCore.BulkExtensions/BulkConfig.cs
- EFCore.BulkExtensions/SqlAdapters/ISqlDialect.cs
- EFCore.BulkExtensions/SqlAdapters/MySql/MySqlAdapter.cs
- EFCore.BulkExtensions/SqlAdapters/MySql/MySqlQueryBuilder.cs
- EFCore.BulkExtensions/SqlAdapters/PostgreSql/PostgreSqlAdapter.cs
- EFCore.BulkExtensions/SqlAdapters/PostgreSql/PostgreSqlQueryBuilder.cs
- EFCore.BulkExtensions/SqlAdapters/SqlAdaptersMapping.cs
- EFCore.BulkExtensions/SqlAdapters/SqlDefaultDialect.cs
- EFCore.BulkExtensions/SqlAdapters/SqlQueryBuilder.cs
- EFCore.BulkExtensions/SqlAdapters/SqlServer/SqlServerAdapter.cs
- EFCore.BulkExtensions/SqlAdapters/SqlServer/SqlServerQueryBuilder.cs
- EFCore.BulkExtensions/SqlAdapters/Sqlite/SqliteAdapter.cs
- EFCore.BulkExtensions/SqlAdapters/Sqlite/SqliteDialect.cs
- EFCore.BulkExtensions/SqlAdapters/Sqlite/SqliteQueryBuilder.cs
- EFCore.BulkExtensions/TableInfo.cs
Hi,
This is a correctly done version of PR #1445 and follow up of #1447.
All references to SqlClient api (SqlCommand, SqlParameter, SqlBulkCopyOptions, SqlBulkCopyColumnOrderHint) have been removed from the shared code.
All usage of SqlCommand and SqlParameter have been replaced with DbParameter and the specific type instanciated in the provider specific QueryBuilder.
The SqlBulkCopyOptions and SqlBulkCopyColumnOrderHint used in BulkConfig was copied.
A better solution would be to use pre-compilation constants for each provider but the modification of the code would then be much more important, so I opted for this approach.
Finally I removed HierarchyId type usage in MySQL provider as it is a specific type of SqlServer, so the code was never reached.
Fix #1418.
> Overhaul DbParameter handling and dependencies trimming in provider specific projects

- Directory.Build.props
- EFCore.BulkExtensions.Core/EFCore.BulkExtensions.Core.csproj
- EFCore.BulkExtensions.Tests/EFCore.BulkExtensions.Tests.csproj
StrongNamer is only used during build and not needed at runtime so declare it as private to not be listed in nuget dependencies.
> Declare StrongNamer as private dependency

- EFCore.BulkExtensions.Core/TableInfo.cs
- EFCore.BulkExtensions.SqlServer/SqlAdapters/SqlServer/SqlServerAdapter.cs
- EFCore.BulkExtensions.Tests/Owned/InheritedOwnedTests.cs
Currently if an entity is owned by multiple parent and one of them happen to be inherited, the following line will not be able to find ownedEntityType because entityType is the inherited class instead of base class
```
if (ownedEntityType == null) // when entity has more then one ownedType (e.g. Address HomeAddress, Address WorkAddress) or one ownedType is in multiple Entities like Audit is usually.
{
ownedEntityType = context.Model.GetEntityTypes().SingleOrDefault(x => x.ClrType == property.PropertyType && x.Name.StartsWith(entityType.Name + "." + property.Name + "#"));
}
```
> Add inherited & owned logic

- EFCore.BulkExtensions.SqlServer/SqlAdapters/SqlServer/SqlServerAdapter.cs
- Make sure nulls are sent to SqlBulkCopy as null, and not as the string "null" in SqlServerAdapter.InnerGetDataTable
- Fixes #1572
> Fix JsonReaderException on BulkInsertAsync when SetOutputIdentity = true, and IsJson column is null

- EFCore.BulkExtensions.Core/TableInfo.cs
- EFCore.BulkExtensions.PostgreSql/SqlAdapters/PostgreSql/PostgreSqlAdapter.cs
- EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs
- EFCore.BulkExtensions.Tests/TestContext.cs
Adds support for Postgresql owned types mapped as json.
Also added Postgresql to the databases tested for CompositeKeys (works without any changes).
Fixes https://github.com/borisdj/EFCore.BulkExtensions/issues/1554
> Added support for Npgsql json owned types

- EFCore.BulkExtensions.PostgreSql/SqlAdapters/PostgreSql/PostgreSqlQueryBuilder.cs
- EFCore.BulkExtensions.Tests/SqlQueryBuilderPostgreSqlTests.cs
fix for #1638 
- include schema name in the DROP INDEX statement
- truncate index name if it exceeds 64 characters
> Fix for issue 1638

- EFCore.BulkExtensions.Core/BulkConfig.cs
- EFCore.BulkExtensions.MySql/SqlAdapters/MySql/MySqlAdapter.cs
- README.md
The MySqlBulkLoader class has a field ConflictOption to specify how to treat duplicates during bulk inserts. Possible values are None, which is the default and current behavior in this project, Ignore and Replace.
This PR lets the user specify the wished for behavior via a new BulkConfig field, which is used when a new MySqlBulkCopy instance gets configured. If nothing is explicitly specified, the behavior is the same as the current one.
> Add support to set ConflictOption in MySqlBulkLoader

- EFCore.BulkExtensions.MySql/SqlAdapters/MySql/MySqlQueryBuilder.cs
- Change SELECT from CONSTRAINT_NAME to COUNT(*) in SQL query
- Fixes bug where existence check relied on non-unique constraint name retrieval
- Ensures deterministic verification of unique constraint existence
- Addresses concurrency issues in constraint creation scenarios
> Replace constraint name check with count verification in MysqlAdapter

- EFCore.BulkExtensions.Core/DbContextBulkTransactionSaveChanges.cs
This change applys the topological sort on deletions to .NET 9 (and future higher versions), as well as .NET 8.
> Apply topological sort on delete to .NET >= 8.0.
